<?php

namespace AppBundle\Repository;

/**
 * MailingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingRepository extends \Doctrine\ORM\EntityRepository
{
}
